accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutPage, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/<int:pk>/', views.profile, name='profile'),
]

catalogues/urls.py
from django.urls import path
from . import views

app_name = 'catalogues'
urlpatterns = [
    path('', views.catalogue, name='catalogue'),
    path('search/', views.search, name='search'),
    path('favourites', views.favourites, name='favourites'),
]

cookbook_v2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('catalogues/', include('catalogues.urls')),
    path('recipes/', include('recipes.urls')),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
]

recipes/urls.py
from django.urls import path
from . import views

app_name='recipes'
urlpatterns = [
    path('new/', views.new, name='new'),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('favourite/<int:pk>/', views.favourite, name='favourite'),
    path('recipe/<int:pk>/', views.recipe, name='recipe'),
]

accounts/models.py
from django.db import models

# Create your models here.

recipes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Ingredient(models.Model):
    name = name = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    name = models.CharField(max_length=50, null=True)
    description = models.TextField(null=True, blank=True)

    # Recipe-Ingredient M-M
    ingredients = models.ManyToManyField(Ingredient)

    # Recipe-User Favourite M-M
    favourite = models.ManyToManyField(User, related_name='favourite', blank=True)

    def __str__(self):
        return self.name

accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CreateUserForm(UserCreationForm):  # remade UserCreationForm for Register Page
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password1', 'password2']

recipes/forms.py
from django.forms import ModelForm
from .models import *

class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = '__all__'
        exclude = ['favourite']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
# Create your views here.
from .forms import CreateUserForm
from .decorators import *


@unauthenticated_user
def register(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')

            group = Group.objects.get(name='cook')
            user.groups.add(group)

            messages.success(request, 'Account was created for ' + username)
            return redirect('accounts:login')

    context = {'form': form}
    return render(request, 'accounts/register.html', context)


@unauthenticated_user
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('main:home')
        else:
            messages.info(request, 'Username or password is incorrect.')

    context = {}
    return render(request, 'accounts/login.html', context)


def logoutPage(request):
    logout(request)
    return redirect('main:home')


@login_required(login_url='accounts:login')
def profile(request, pk):
    user = User.objects.get(id=pk)

    groups = user.groups.all()

    context = {'user': user, 'groups': groups}
    return render(request, 'accounts/profile.html', context)

catalogues/views.py
from django.shortcuts import render
# Create your views here.
from recipes.models import Recipe
from recipes.filters import RecipeFilter


def catalogue(request):
    recipes = Recipe.objects.all()

    context = {'recipes': recipes}
    return render(request, 'catalogues/catalogue.html', context)


def favourites(request):
    user = request.user
    recipes = user.favourite.all()

    context = {'recipes': recipes}
    return render(request, 'catalogues/favourites.html', context)


def search(request):
    recipes = Recipe.objects.all()

    recipeFilter = RecipeFilter(request.GET, queryset=recipes)
    recipes = recipeFilter.qs

    context = {'recipeFilter': recipeFilter, 'recipes': recipes}
    return render(request, 'catalogues/search.html', context)

main/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'main/home.html')


def about(request):
    return render(request, 'main/about.html')

recipes/views.py
from django.contrib import auth, messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
# Create your views here.
from .models import *
from .forms import RecipeForm
from accounts.decorators import *


@login_required(login_url='accounts:login')
def new(request):
    form = RecipeForm()
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('catalogues:catalogue')

    context = {'form': form}
    return render(request, 'recipes/new.html', context)


@login_required(login_url='accounts:login')
def update(request, pk):
    recipe = Recipe.objects.get(id=pk)
    form = RecipeForm(instance=recipe)
    if request.method == 'POST':
        form = RecipeForm(request.POST, instance=recipe)
        if form.is_valid():
            form.save()
            return redirect('catalogues:catalogue')

    context = {'form': form}
    return render(request, 'recipes/new.html', context)


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def delete(request, pk):
    recipe = Recipe.objects.get(id=pk)
    if request.method == 'POST':
        recipe.delete()
        return redirect('catalogues:catalogue')

    context = {'recipe': recipe}
    return render(request, 'recipes/delete.html', context)


@login_required(login_url='accounts:login')
def favourite(request, pk):
    recipe = Recipe.objects.get(id=pk)

    if recipe.favourite.filter(id=request.user.id).exists():
        recipe.favourite.remove(request.user)
    else:
        recipe.favourite.add(request.user)

    return redirect('recipes:recipe', recipe.pk)


def recipe(request, pk):
    recipe = Recipe.objects.get(id=pk)
    ingredients = recipe.ingredients.all()

    is_favourite = False
    if recipe.favourite.filter(id=request.user.id).exists():
        is_favourite = True

    context = {'recipe': recipe, 'ingredients': ingredients, 'is_favourite': is_favourite}
    return render(request, 'recipes/recipe.html', context)

accounts/templates/accounts/base.html
<!doctype html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block title %}
    Login page
{% endblock %}

{% block content %}
    <div class="container">
        <main class="form-signin">
          <form action="" method="POST">
          {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal">Login</h1>
            <div class="form-group row-sm-3">
                <div class="form-group row-sm-3">
                    <div class="input-group mb-2 row-sm-3">
                        <div class="input-group-prepend">
                            <div class="input-group-text">@</div>
                        </div>
                        <input type="text" name="username" placeholder="Username" class="form-control">
                    </div>
                </div>
            </div>
            <div class="form-group row-sm-3">
                <div class="row-sm-3">
                    <input type="password" name="password" placeholder="Password" class="form-control">
                </div>
            </div>

            <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                <div class="btn-group mr-2" role="group" aria-label="First group">
                  <input class="btn btn-outline-primary" type="submit" name="Login">
                  <a class="btn btn-outline-secondary" href="{% url 'main:home' %}">Back</a>
                </div>
            </div>

              {% for message in messages %}
                    <p id="messages">{{ message }}</p>
              {% endfor %}

              <div class="form-group row mt-4">
                  <div class="d-flex justify-content-left links">
                      Don't have an account? <a class="ml-1" href="{% url 'accounts:register' %}">Register</a>
                  </div>
              </div>
          </form>
        </main>
    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %}

{% block title %}
    Profile page
{% endblock %}

{% block content %}
    {% include 'navbar.html' %}
    <div class="container">

        <h1>Profile</h1>

        <div class="card-body">
            <div class="row">
                <div class="col-sm-3">
                    <h6 class="mb-0">Username</h6>
                </div>
                <div class="col-sm-9 text-secondary">{{ user.username }}</div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <h6 class="mb-0">Full Name</h6>
                </div>
                <div class="col-sm-9 text-secondary">{{ user.get_full_name }}</div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <h6 class="mb-0">Group</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    {% for group in groups %}
                        {{ group.name }}
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-2" role="group" aria-label="First group">
                <a class="btn btn-outline-success" href="{% url 'recipes:new' %}">New Recipe</a>
                <a class="btn btn-outline-warning" href="{% url 'catalogues:favourites' %}">Favourites</a>
                <a class="btn btn-outline-secondary" href="{% url 'main:home' %}">Back</a>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}

{% block title %}
    Register page
{% endblock %}

{% block content %}
    <<div class="container">
        <main class="form-signin">
          <form action="" method="POST">
              {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal">Register</h1>
            <div class="form-group row-sm-3">
                <div class="form-group row-sm-3">
                    {{ form.username.label }}
                    <div class="input-group mb-2 row-sm-3">
                        <div class="input-group-prepend">
                            <div class="input-group-text">@</div>
                        </div>
                        {{ form.username }}
                    </div>
                </div>
            </div>

              <div class="form-group row-sm-3">
                  <div class="row-sm-3">
                      {{ form.first_name.label }}
                    <div class="row-sm-2">
                        {{ form.first_name }}
                    </div>
                  </div>

                  <div class="form-group row-sm-3">
                      {{ form.last_name.label }}
                    <div class="row-sm-2">
                        {{ form.last_name }}
                    </div>
                  </div>
              </div>

              <div class="form-group row-sm-3">
                  <div class="row-sm-3">
                      {{ form.password1.label }}
                    <div class="row-sm-2">
                        {{ form.password1 }}
                    </div>
                  </div>

                  <div class="form-group row-sm-3">
                      {{ form.password2.label }}
                    <div class="row-sm-2">
                        {{ form.password2 }}
                    </div>
                  </div>
              </div>

            <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                <div class="btn-group mr-2" role="group" aria-label="First group">
                  <input class="btn btn-outline-primary" type="submit" name="Create user">
                  <a class="btn btn-outline-secondary" href="{% url 'main:home' %}">Back</a>
                </div>
            </div>

              {{ form.errors }}

              <div class="form-group row mt-4">
                  <div class="d-flex justify-content-left links">
                      Already have an account? <a class="ml-1" href="{% url 'accounts:login' %}">Login</a>
                  </div>
              </div>
          </form>
        </main>
    </div>
{% endblock %}

catalogues/templates/catalogues/base.html
<!doctype html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

catalogues/templates/catalogues/catalogue.html
{% extends 'catalogues/base.html' %}

{% block title %}
    Catalogue page
{% endblock %}

{% block content %}
    <h1>Catalogue</h1>
    <table class="table mt-4 table-hover">
        <thead>
        <tr>
            <th>Recipe</th>
            {% if request.user.is_authenticated %}
                <th>Favourite</th>
            {% endif %}
            <th></th>
            {% if request.user.is_staff %}
            <th></th>
            {% endif %}
        </tr>
        </thead>
        {% for recipe in recipes %}
            <tbody>
            <tr>
                <td><h5>{{ recipe.name }}</h5></td>
                {% if request.user.is_authenticated %}
                    {% if recipe.favourite.count == 1 %}
                        <td>In Favourites: {{ recipe.favourite.count }} time</td>
                    {% else %}
                        <td>In Favourites: {{ recipe.favourite.count }} times</td>
                    {% endif %}
                {% endif %}
                <td><a class="btn btn-outline-info" href="{% url 'recipes:recipe' recipe.pk %}">View</a></td>
                {% if request.user.is_staff %}
                    <td><a class="btn btn-outline-danger" href="{% url 'recipes:delete' recipe.pk %}">Delete</a></td>
                {% endif %}
            </tr>
            </tbody>
        {% endfor %}
    </table>
{% endblock %}

catalogues/templates/catalogues/favourites.html
{% extends 'catalogues/base.html' %}

{% block title %}
    Favourites page
{% endblock %}

{% block content %}
    <h1>Favourites</h1>
    <table class="table">
        <tr>
            <th>Recipe</th>
            <th></th>
            {% if request.user.is_staff %}
            <th></th>
            {% endif %}
        </tr>

        {% for recipe in recipes %}
            <tr>
                <td><h5>{{ recipe.name }}</h5></td>
                <td><a class="btn btn-outline-info" href="{% url 'recipes:recipe' recipe.pk %}">View</a></td>
                {% if request.user.is_staff %}
                    <td><a class="btn btn-outline-danger" href="{% url 'recipes:delete' recipe.pk %}">Delete</a></td>
                {% endif %}
            </tr>
        {% empty %}
            <tr>
                <td>No Favourite Recipes found.</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

catalogues/templates/catalogues/search.html
{% extends 'catalogues/base.html' %}

{% block title %}
    Search page
{% endblock %}

{% block content %}
    <h1>Search</h1>

    <form method="GET">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-2">
                    <h6 class="text-secondary">Name: {{ recipeFilter.form.name }}</h6>
                </div>
                <div class="col-sm-1 ml-4">
                    <h6 class=" text-secondary">Ingredients: {{ recipeFilter.form.ingredients }}</h6>
                </div>
                <div class="col-sm-1 text-secondary ml-3 mt-3"><button class="btn btn-lg btn-outline-secondary" type="submit">Search</button></div>
            </div>
        </div>
    </form>

    <table class="table mt-4 table-hover">
        {% for recipe in recipes %}
            <tbody>
            <tr>
                <td><h5>{{ recipe.name }}</h5></td>
                {% if request.user.is_authenticated %}
                    {% if recipe.favourite.count == 1 %}
                        <td>In Favourites: {{ recipe.favourite.count }} time</td>
                    {% else %}
                        <td>In Favourites: {{ recipe.favourite.count }} times</td>
                    {% endif %}
                {% endif %}
                <td><a class="btn btn-outline-info" href="{% url 'recipes:recipe' recipe.pk %}">View</a></td>
                {% if request.user.is_authenticated %}
                    <td><a class="btn btn-outline-success" href="{% url 'recipes:new' %}">Edit</a></td>
                {% endif %}
                {% if request.user.is_staff %}
                    <td><a class="btn btn-outline-danger" href="{% url 'recipes:delete' recipe.pk %}">Delete</a></td>
                {% endif %}
            </tr>
            <tbody>
        {% endfor %}
    </table>
{% endblock %}

main/templates/main/about.html
{% extends 'main/base.html' %}

{% block title %}
    About page
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>This is a project for 3d Semester.</p>
    <p>
        <h4>Core technologies:<br></h4>
            <div class="card">
                 <ul class="list-group list-group-flush">
                     <div class="card-body">
                          <li class="list-group-item">Python</li>
                          <li class="list-group-item">Django</li>
                          <li class="list-group-item">django-filters</li>
                          <li class="list-group-item">Bootstrap</li>
                     </div>
                </ul>
            </div>

    </p>
    <p>
        <h4>Structure:<br></h4>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                  <div class="card">
                      <h6 class="ml-3 mt-2">Main</h6>
                      <ul class="list-group list-group-flush">
                          <div class="card-body">
                              <li class="list-group-item">home</li>
                              <li class="list-group-item">about</li>
                          </div>
                      </ul>
                  </div>
              </li>
              <li class="list-group-item">
                  <div class="card">
                      <h6 class="ml-3 mt-2">Accounts</h6>
                      <ul class="list-group list-group-flush">
                          <div class="card-body">
                              <li class="list-group-item">register</li>
                              <li class="list-group-item">login</li>
                              <li class="list-group-item">profile</li>
                          </div>
                      </ul>
                  </div>
              </li>
              <li class="list-group-item card">
                  <div class="card">
                      <h6 class="ml-3 mt-2">Catalogues</h6>
                      <ul class="list-group list-group-flush">
                          <div class="card-body">
                              <li class="list-group-item">catalogue</li>
                              <li class="list-group-item">search</li>
                              <li class="list-group-item">favourites</li>
                          </div>
                      </ul>
                  </div>
              </li>
              <li class="list-group-item card">
                  <div class="card">
                      <h6 class="ml-3 mt-2">Recipes</h6>
                      <ul class="list-group list-group-flush">
                          <div class="card-body">
                              <li class="list-group-item">new/edit</li>
                              <li class="list-group-item">delete</li>
                              <li class="list-group-item">recipe</li>
                          </div>
                      </ul>
                  </div>
              </li>

            </ul>
    </p>
    <p>
        Made by:<br>
        Alexander Loginov<br>
        gr. P3222
    </p>
{% endblock %}

main/templates/main/base.html
<!doctype html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

main/templates/main/home.html
{% extends 'main/base.html' %}

{% block title %}
    Home page
{% endblock %}

{% block content %}
    <div class="jumbotron">
      {% if request.user.is_authenticated %}
        <h1 class="display-4">Hello, {{ request.user.get_full_name }}</h1>
      {% else %}
        <h1 class="display-4">Welcome to the Cookbook!</h1>
      {% endif %}
      <p class="lead">This is a recipe catalogue for everybody.</p>
      <hr class="my-4">
      <p>Click the button to start.</p>
      <p class="lead">
        {% if request.user.is_authenticated %}
            <a class="btn btn-primary btn-lg" href="{% url 'accounts:profile' user.pk %}" role="button">Go to Profile</a>
        {% else %}
            <a class="btn btn-primary btn-lg" href="{% url 'catalogues:catalogue' %}" role="button">Go to Catalogue</a>
        {% endif %}
      </p>
    </div>
{% endblock %}

recipes/templates/recipes/base.html
<!doctype html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

recipes/templates/recipes/delete.html
{% extends 'recipes/base.html' %}

{% block title %}
    Delete recipe
{% endblock %}

{% block content %}
    <div class="container">
        <h5 class="mt-4 mb-4">Are you sure want to delete "{{ recipe }}"?</h5>
        <form action="" method="POST">
            {% csrf_token %}

            <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                <div class="btn-group mr-2" role="group" aria-label="First group">
                    <input class="btn btn-outline-danger" type="submit" name="Confirm">
                    <a class="btn btn-outline-secondary" href="{% url 'catalogues:catalogue' %}">Cancel</a>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

recipes/templates/recipes/new.html
{% extends 'recipes/base.html' %}

{% block title %}
    Editing
{% endblock %}

{% block content %}
    <div class="container">
        <h1>New recipe</h1>
        <form action="" method="POST">
            {% csrf_token %}

            <div class="card card-body">
                <div class="list-group list-group-flush">
                    <div class="row list-group-item">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Name</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">{{ form.name }}</div>
                    </div>
                    <div class="row list-group-item">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Description</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">{{ form.description }}</div>
                    </div>
                    <div class="row list-group-item">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Ingredients</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">{{ form.ingredients }}</div>
                    </div>
                </div>
            </div>

            <div class="btn-toolbar mt-4" role="toolbar" aria-label="Toolbar with button groups">
                <div class="btn-group mr-2" role="group" aria-label="First group">
                    <input class="btn btn-outline-info" type="submit" name="Submit">
                    <a class="btn btn-outline-secondary" href="{% url 'catalogues:catalogue' %}">Cancel</a>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

recipes/templates/recipes/recipe.html
{% extends 'recipes/base.html' %}

{% block title %}
    Recipe page
{% endblock %}

{% block content %}
    {% include 'navbar.html' %}
    <div class="container">
        <h1>{{ recipe.name }}
        {% if request.user.is_authenticated %}
            {% if is_favourite %}
                <a class="btn btn-lg btn-warning ml-auto mb-2" href="{% url 'recipes:favourite' recipe.pk %}">Favourite</a>
            {% else %}
                <a class="btn btn-lg btn-outline-warning ml-auto mb-2" href="{% url 'recipes:favourite' recipe.pk %}">Favourite</a>
            {% endif %}
        {% endif %}
        </h1>
        <table class="table mt-3 table-hover">
            <thead>
            <tr>
                <th>Recipe</th>
                <th>Ingredients</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ recipe.name }}</td>
                <td>
                    {% for ingredient in ingredients %}
                        {{ ingredient.name }};
                    {% endfor %}
                </td>
            </tr>
            </tbody>
        </table>

        <h5>Description</h5>
        <p>{{ recipe.description }}</p>

        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-2" role="group" aria-label="First group">
                {% if request.user.is_authenticated %}
                    <a class="btn btn-outline-success" href="{% url 'recipes:update' recipe.pk %}">Edit</a>
                {% endif %}
                {% if request.user.is_staff %}
                    <a class="btn btn-outline-danger" href="{% url 'recipes:delete' recipe.pk %}">Delete</a>
                {% endif %}
                <a class="btn btn-outline-secondary" href="{% url 'catalogues:catalogue' %}">Back</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/navbar.html
<header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-5 bg-body border-bottom shadow-sm">
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top justify-content-between">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:home' %}">Cookbook</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'catalogues:catalogue' %}">Catalogue</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'catalogues:search' %}">Search</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'main:about' %}">About</a>
            </li>
              {% if request.user.is_anonymous %}
                <li class="nav-item"><a class="btn btn-outline-warning ml-auto" href="{% url 'accounts:register' %}">Register</a></li>
                <li class="nav-item"><a class="btn btn-outline-info ml-1" href="{% url 'accounts:login' %}">Login</a></li>
              {% endif %}
              {% if request.user.is_authenticated %}
                <li class="nav-item"><a class="btn btn-outline-success ml-auto" href="{% url 'accounts:profile' user.pk %}">Profile</a></li>
                <li class="nav-item"><a class="btn btn-outline-primary ml-1" href="{% url 'accounts:logout' %}">Logout</a></li>
              {% endif %}
          </ul>
        </div>
      </div>
    </nav>
</header>